// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Event event
// swagger:model Event
type Event struct {
	Data

	// this refers to the type of event being sent,such as 'session_start', 'session_end', 'link_clicked', etc
	EventType string `json:"event_type,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *Event) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Data
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Data = aO0

	// AO1
	var dataAO1 struct {
		EventType string `json:"event_type,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.EventType = dataAO1.EventType

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m Event) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Data)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		EventType string `json:"event_type,omitempty"`
	}

	dataAO1.EventType = m.EventType

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Data
	if err := m.Data.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Event) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Event) UnmarshalBinary(b []byte) error {
	var res Event
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
