// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Params A key-value dictionary where the key must be a string but the value can be of any data type
// swagger:model Params
type Params map[string]interface{}

// Validate validates this params
func (m Params) Validate(formats strfmt.Registry) error {
	return nil
}
