version: "3.6"
services:
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  server:
    image: gsevent-server
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - .:/app
    links:
      - redis
    ports:
      - 8080:8080
    environment:
      - HTTP_PORT=8080
      - LOG_LEVEL=debug
      - SERVICE_NAME=gsevent
      - REDIS_ADDRESS=redis:6379
      - NEW_FILE_INTERVAL=1h
      - MAX_WORKERS=1000
